name: amigo
description: Exploring new words in different languages.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Installing Firebase
  cloud_firestore: ^0.12.1

  # Implement Google Sign In
  google_sign_in: ^4.0.1+3

  # Integrate Agora for Video...
  agora_rtc_engine: ^0.9.5

  # Integrate Flare...
  flare_flutter: ^1.3.12

flutter:

  uses-material-design: true

  assets:
    - amigoLogo.png
    - amigoUser.jpg
    - assets/animations/success.flr

  fonts:
     - family: monsterrat
       fonts:
         - asset: fonts/Montserrat-Regular.ttf